matrix:
  include:
    - language: node_js
      node_js:
      - stable
      before_install: cd visualizer
      cache:
        directories:
        - node_modules
      script:
      - npm test
      before_deploy:
      - ./build.sh
    - language: java
      jdk: openjdk8
      before_install: cd RobotReader
      script:
        - gradle build

    
