version: "3.3"
services:
  influx:
    image: influxdb
    ports: 
      - 8086:8086
    volumes:
      - influxdata:/var/lib/influxdb
  robot-reader:
    build: RobotReader/
    links: 
      - influx
    depends_on: 
      - influx
    command: -influxDbServerAddress influx
  visualizer:
    build: JSVisualizer/
    ports:
      - 9000:80
    links:
      - influx
    depends_on:
      - influx
  chronograf:
    image: chronograf
    command: --influxdb-url=http://influx:8086
    ports:
      - 9001:8888
volumes:
 influxdata: