version: "3.3"
services:
  influx:
    image: influxdb
    ports: 
      - 8086:8086
    volumes:
      - influxdata:/var/lib/influxdb
  robot-reader:
    build: RobotReader/
    links: 
      - influx
    depends_on: 
      - influx
    command: -influxDbServerAddress influx
  visualizer:
    build: JSVisualizer/
    ports:
      - 8000:8000
    links:
      - influx
    depends_on:
      - influx
volumes:
 influxdata: